- name: Add disk for var storage
  delegate_to: localhost
  ovirt_disk:
    name: "{{ inventory_hostname_short }}{{ ovirt_hostname_suffix | default('.' + ovirt_user_identifier) }}.{{ ovirt_storage_name }}.disk"
    vm_name: "{{ inventory_hostname_short }}{{ ovirt_hostname_suffix | default('.' + ovirt_user_identifier) }}"
    state: attached
    size: "{{ ovirt_storage_size }}"
    format: cow
    interface: virtio_scsi
    storage_domain: vmstore
    bootable: "{{ ovirt_storage_bootable }}"
    auth:
      hostname: "{{ ovirt_host_name }}"
      insecure: yes
      url: "https://{{ ovirt_host_name }}/ovirt-engine/api"
      username: "{{ ovirt_host_user }}"
      password: "{{ ovirt_host_pass }}"