- name: Create VM
  delegate_to: localhost
  ovirt_vm:
    # The machine behaves differently starting from ansible vs. the ui.
    # From ansible the cloud_init does not run.
    #state: running
    timeout: 1800
    name: "{{ inventory_hostname_short }}{{ ovirt_hostname_suffix | default('.' + ovirt_user_identifier) }}"
    comment: "{{ ovirt_comment }}"
    template: "{{ ovirt_template }}"
    clone: yes
    cluster: Default
    memory: "{{ ovirt_memory }}"
    memory_max: "{{ ovirt_memory }}"
    memory_guaranteed: "{{ ovirt_memory }}"
    cpu_cores: "{{ ovirt_cpu_cores }}"
    cpu_sockets: "{{ ovirt_cpu_sockets }}"
    cpu_threads: 1
    type: server
    operating_system: "{{ ovirt_os }}"
    high_availability: false
    boot_devices: "{{ ovirt_boot_devices }}"
    auth:
      hostname: "{{ ovirt_host_name }}"
      insecure: yes
      url: "https://{{ ovirt_host_name }}/ovirt-engine/api"
      username: "{{ ovirt_host_user }}"
      password: "{{ ovirt_host_pass }}"
    wait: true

- name: sleep for 300 seconds and continue with play
  wait_for:
    timeout: 5
  delegate_to: localhost

- name: "Attach ISO image to cdrom"
  delegate_to: localhost
  ovirt_vm:
    # The machine behaves differently starting from ansible vs. the ui.
    # From ansible the cloud_init does not run.
    #state: running
    timeout: 1800
    name: "{{ inventory_hostname_short }}{{ ovirt_hostname_suffix | default('.' + ovirt_user_identifier) }}"
    comment: "{{ ovirt_comment }}"
    cd_iso: "{{ ovirt_cd_iso }}"
    auth:
      hostname: "{{ ovirt_host_name }}"
      insecure: yes
      url: "https://{{ ovirt_host_name }}/ovirt-engine/api"
      username: "{{ ovirt_host_user }}"
      password: "{{ ovirt_host_pass }}"
    wait: true
  when: ovirt_cd_iso != ""
